// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module AsyncMemArbiter(
  input         clock,
  input         reset,
  input         io_in_0_rd,
  input         io_in_0_wr,
  input  [6:0]  io_in_0_addr,
  input  [15:0] io_in_0_din,
  output [15:0] io_in_0_dout,
  output        io_in_0_wait_n,
  output        io_in_0_valid,
  input         io_in_1_rd,
  input         io_in_1_wr,
  input  [6:0]  io_in_1_addr,
  input  [15:0] io_in_1_din,
  output [15:0] io_in_1_dout,
  output        io_in_1_wait_n,
  output        io_in_1_valid,
  output        io_out_rd,
  output        io_out_wr,
  output [6:0]  io_out_addr,
  output [15:0] io_out_din,
  input  [15:0] io_out_dout,
  input         io_out_wait_n,
  input         io_out_valid
);

  reg         busyReg;
  reg  [1:0]  indexReg;
  wire [1:0]  index_enc =
    io_in_0_rd | io_in_0_wr ? 2'h1 : {io_in_1_rd | io_in_1_wr, 1'h0};
  wire [1:0]  chosen = busyReg ? indexReg : index_enc;
  wire        io_out_rd_0 = chosen[0] & io_in_0_rd | chosen[1] & io_in_1_rd;
  wire [6:0]  _io_out_mem_addr_T = chosen[0] ? io_in_0_addr : 7'h0;
  wire [6:0]  _io_out_mem_addr_T_1 = chosen[1] ? io_in_1_addr : 7'h0;
  wire [15:0] _io_out_mem_din_T = chosen[0] ? io_in_0_din : 16'h0;
  wire [15:0] _io_out_mem_din_T_1 = chosen[1] ? io_in_1_din : 16'h0;
  wire        _io_out_io_in_1_wait_n_T = chosen == 2'h0;
  wire        effectiveRequest = ~busyReg & io_out_rd_0 & io_out_wait_n;
  always @(posedge clock) begin
    if (reset) begin
      busyReg <= 1'h0;
      indexReg <= 2'h0;
    end
    else begin
      busyReg <= ~io_out_valid & (effectiveRequest | busyReg);
      if (io_out_valid | ~effectiveRequest) begin
      end
      else
        indexReg <= index_enc;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        busyReg = _RANDOM[/*Zero width*/ 1'b0][0];
        indexReg = _RANDOM[/*Zero width*/ 1'b0][2:1];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_0_dout = io_out_dout;
  assign io_in_0_wait_n = (_io_out_io_in_1_wait_n_T | chosen[0]) & io_out_wait_n;
  assign io_in_0_valid = chosen[0] & io_out_valid;
  assign io_in_1_dout = io_out_dout;
  assign io_in_1_wait_n = (_io_out_io_in_1_wait_n_T | chosen[1]) & io_out_wait_n;
  assign io_in_1_valid = chosen[1] & io_out_valid;
  assign io_out_rd = io_out_rd_0;
  assign io_out_wr = chosen[0] & io_in_0_wr | chosen[1] & io_in_1_wr;
  assign io_out_addr = _io_out_mem_addr_T | _io_out_mem_addr_T_1;
  assign io_out_din = _io_out_mem_din_T | _io_out_mem_din_T_1;
endmodule

