// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module AudioMixer(
  input         clock,
  input  [13:0] io_in_4,
  input  [13:0] io_in_3,
  input  [15:0] io_in_2,
  input  [15:0] io_in_1,
  input  [15:0] io_in_0,
  output [15:0] io_out
);

  reg  [21:0] io_out_REG;
  wire [18:0] _sum_T_3 = 19'({{3{io_in_1[15]}}, io_in_1} * 19'h3);
  wire [21:0] _sum_T_7 = 22'({{6{io_in_3[13]}}, io_in_3, 2'h0} * 22'h1A);
  wire [22:0] _sum_T_10 =
    23'({{3{io_in_0[15]}}, io_in_0, 4'h0} + {{4{_sum_T_3[18]}}, _sum_T_3});
  wire [23:0] _sum_T_11 =
    24'({_sum_T_10[22], _sum_T_10} + {{4{io_in_2[15]}}, io_in_2, 4'h0});
  wire [24:0] _sum_T_12 = 25'({_sum_T_11[23], _sum_T_11} + {{3{_sum_T_7[21]}}, _sum_T_7});
  wire [25:0] sum = 26'({_sum_T_12[24], _sum_T_12} + {{6{io_in_4[13]}}, io_in_4, 6'h0});
  wire [21:0] _io_out_T_1 = $signed(sum[25:4]) < -22'sh8000 ? 22'h3F8000 : sum[25:4];
  always @(posedge clock)
    io_out_REG <= $signed(_io_out_T_1) < 22'sh7FFF ? _io_out_T_1 : 22'h7FFF;
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        io_out_REG = _RANDOM[/*Zero width*/ 1'b0][21:0];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out = io_out_REG[15:0];
endmodule

