// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BurstBuffer(
  input         clock,
  input         reset,
  input         io_in_wr,
  input  [26:0] io_in_addr,
  input  [15:0] io_in_din,
  output        io_out_wr,
  output [31:0] io_out_addr,
  output [63:0] io_out_din,
  input         io_out_burstDone
);

  reg         writePendingReg;
  reg  [63:0] lineReg_words_0;
  reg  [26:0] addrReg;
  reg         busyReg;
  reg  [1:0]  wordCounter;
  wire [15:0] words_3 = (&wordCounter) ? io_in_din : lineReg_words_0[63:48];
  wire [15:0] words_2 = wordCounter == 2'h2 ? io_in_din : lineReg_words_0[47:32];
  wire [15:0] words_1 = wordCounter == 2'h1 ? io_in_din : lineReg_words_0[31:16];
  wire [15:0] words_0 = wordCounter == 2'h0 ? io_in_din : lineReg_words_0[15:0];
  wire        latchData = io_in_wr & ~writePendingReg;
  always @(posedge clock) begin
    if (reset) begin
      writePendingReg <= 1'h0;
      busyReg <= 1'h0;
      wordCounter <= 2'h0;
    end
    else begin
      writePendingReg <=
        ~io_out_burstDone & (latchData & (&wordCounter) | writePendingReg);
      busyReg <= ~io_out_burstDone & (io_in_wr | busyReg);
      if (latchData)
        wordCounter <= 2'(wordCounter + 2'h1);
    end
    if (latchData)
      lineReg_words_0 <= {words_3, words_2, words_1, words_0};
    if (io_in_wr & ~busyReg)
      addrReg <= io_in_addr;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        writePendingReg = _RANDOM[2'h0][0];
        lineReg_words_0 = {_RANDOM[2'h0][31:1], _RANDOM[2'h1], _RANDOM[2'h2][0]};
        addrReg = _RANDOM[2'h2][27:1];
        busyReg = _RANDOM[2'h2][28];
        wordCounter = _RANDOM[2'h2][30:29];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_wr = writePendingReg;
  assign io_out_addr = {5'h0, addrReg[26:3], 3'h0};
  assign io_out_din = lineReg_words_0;
endmodule

