// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BurstReadDMA(
  input         clock,
  input         reset,
  input         io_start,
  output        io_busy,
  output        io_in_rd,
  output [31:0] io_in_addr,
  input  [63:0] io_in_dout,
  input         io_in_wait_n,
  input         io_in_valid,
  input         io_in_burstDone,
  output        io_out_wr,
  output [31:0] io_out_addr,
  output [63:0] io_out_din,
  input         io_out_wait_n
);

  wire        _fifo_io_enq_valid;
  wire        _fifo_io_deq_valid;
  wire [5:0]  _fifo_io_count;
  reg         readEnableReg;
  reg         writeEnableReg;
  reg         readPendingReg;
  wire        busy = readEnableReg | writeEnableReg;
  wire        start = io_start & ~busy;
  wire        read = readEnableReg & ~readPendingReg & _fifo_io_count < 6'h11;
  wire        write = writeEnableReg & _fifo_io_deq_valid;
  wire        effectiveWrite = write & io_out_wait_n;
  reg  [21:0] wordCounter;
  reg  [17:0] burstCounter;
  always @(posedge clock) begin
    if (reset) begin
      readEnableReg <= 1'h0;
      writeEnableReg <= 1'h0;
      readPendingReg <= 1'h0;
      wordCounter <= 22'h0;
      burstCounter <= 18'h0;
    end
    else begin
      readEnableReg <= start | ~(io_in_burstDone & (&burstCounter)) & readEnableReg;
      writeEnableReg <= start | ~(effectiveWrite & (&wordCounter)) & writeEnableReg;
      readPendingReg <= ~io_in_burstDone & (read & io_in_wait_n | readPendingReg);
      if (effectiveWrite)
        wordCounter <= 22'(wordCounter + 22'h1);
      if (io_in_burstDone)
        burstCounter <= 18'(burstCounter + 18'h1);
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;
        end
        readEnableReg = _RANDOM[1'h0][0];
        writeEnableReg = _RANDOM[1'h0][1];
        readPendingReg = _RANDOM[1'h0][2];
        wordCounter = _RANDOM[1'h0][24:3];
        burstCounter = {_RANDOM[1'h0][31:25], _RANDOM[1'h1][10:0]};
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign _fifo_io_enq_valid = io_in_valid & readPendingReg;
  Queue32_UInt64 fifo (
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (_fifo_io_enq_valid),
    .io_enq_bits  (io_in_dout),
    .io_deq_ready (effectiveWrite),
    .io_deq_valid (_fifo_io_deq_valid),
    .io_deq_bits  (io_out_din),
    .io_count     (_fifo_io_count),
    .io_flush     (start)
  );
  assign io_busy = busy;
  assign io_in_rd = read;
  assign io_in_addr = {7'h0, burstCounter, 7'h0};
  assign io_out_wr = write;
  assign io_out_addr = {7'h0, wordCounter, 3'h0};
endmodule

