// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BurstWriteDMA(
  input         clock,
  input         reset,
  input         io_start,
  output        io_out_wr,
  output [31:0] io_out_addr,
  output [63:0] io_out_din,
  input         io_out_wait_n,
  input         io_out_burstDone
);

  wire        _fifo_io_enq_ready;
  wire [6:0]  _fifo_io_count;
  reg         readEnableReg;
  reg         writeEnableReg;
  reg         readPendingReg;
  reg         writePendingReg;
  wire        start = io_start & ~(readEnableReg | writeEnableReg);
  wire        write = writeEnableReg & (writePendingReg | _fifo_io_count == 7'h40);
  wire        effectiveWrite = write & io_out_wait_n;
  reg  [14:0] wordCounter;
  reg  [8:0]  burstCounter;
  wire        read =
    readEnableReg & (~readPendingReg & _fifo_io_enq_ready | _fifo_io_count < 7'h3F);
  always @(posedge clock) begin
    if (reset) begin
      readEnableReg <= 1'h0;
      writeEnableReg <= 1'h0;
      readPendingReg <= 1'h0;
      writePendingReg <= 1'h0;
      wordCounter <= 15'h0;
      burstCounter <= 9'h0;
    end
    else begin
      readEnableReg <= start | ~(read & (&wordCounter)) & readEnableReg;
      writeEnableReg <= start | ~(io_out_burstDone & (&burstCounter)) & writeEnableReg;
      readPendingReg <= read;
      writePendingReg <= ~io_out_burstDone & (effectiveWrite | writePendingReg);
      if (read)
        wordCounter <= 15'(wordCounter + 15'h1);
      if (io_out_burstDone)
        burstCounter <= 9'(burstCounter + 9'h1);
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        readEnableReg = _RANDOM[/*Zero width*/ 1'b0][0];
        writeEnableReg = _RANDOM[/*Zero width*/ 1'b0][1];
        readPendingReg = _RANDOM[/*Zero width*/ 1'b0][2];
        writePendingReg = _RANDOM[/*Zero width*/ 1'b0][3];
        wordCounter = _RANDOM[/*Zero width*/ 1'b0][18:4];
        burstCounter = _RANDOM[/*Zero width*/ 1'b0][27:19];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue64_UInt64 fifo (
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (_fifo_io_enq_ready),
    .io_enq_valid (readPendingReg),
    .io_deq_ready (effectiveWrite),
    .io_deq_bits  (io_out_din),
    .io_count     (_fifo_io_count),
    .io_flush     (start)
  );
  assign io_out_wr = write;
  assign io_out_addr = {14'h0, burstCounter, 9'h0};
endmodule

