// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BurstBuffer_1(
  input         clock,
  input         reset,
  input         io_in_wr,
  input  [31:0] io_in_addr,
  input  [63:0] io_in_din,
  output        io_in_wait_n,
  output        io_out_wr,
  output [24:0] io_out_addr,
  output [15:0] io_out_din,
  input         io_out_wait_n,
  input         io_out_burstDone
);

  reg         writePendingReg;
  reg  [15:0] lineReg_words_0;
  reg  [15:0] lineReg_words_1;
  reg  [15:0] lineReg_words_2;
  reg  [15:0] lineReg_words_3;
  reg  [31:0] addrReg;
  reg         busyReg;
  reg  [1:0]  burstCounter;
  reg  [15:0] casez_tmp;
  always @(*) begin
    casez (burstCounter)
      2'b00:
        casez_tmp = lineReg_words_0;
      2'b01:
        casez_tmp = lineReg_words_1;
      2'b10:
        casez_tmp = lineReg_words_2;
      default:
        casez_tmp = lineReg_words_3;
    endcase
  end // always @(*)
  wire        latchData = io_in_wr & ~writePendingReg;
  always @(posedge clock) begin
    if (reset) begin
      writePendingReg <= 1'h0;
      busyReg <= 1'h0;
      burstCounter <= 2'h0;
    end
    else begin
      writePendingReg <= ~io_out_burstDone & (latchData | writePendingReg);
      busyReg <= ~io_out_burstDone & (io_in_wr | busyReg);
      if (writePendingReg & io_out_wait_n)
        burstCounter <= 2'(burstCounter + 2'h1);
    end
    if (latchData) begin
      lineReg_words_0 <= io_in_din[15:0];
      lineReg_words_1 <= io_in_din[31:16];
      lineReg_words_2 <= io_in_din[47:32];
      lineReg_words_3 <= io_in_din[63:48];
    end
    if (io_in_wr & ~busyReg)
      addrReg <= io_in_addr;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;
        end
        writePendingReg = _RANDOM[2'h0][0];
        lineReg_words_0 = _RANDOM[2'h0][16:1];
        lineReg_words_1 = {_RANDOM[2'h0][31:17], _RANDOM[2'h1][0]};
        lineReg_words_2 = _RANDOM[2'h1][16:1];
        lineReg_words_3 = {_RANDOM[2'h1][31:17], _RANDOM[2'h2][0]};
        addrReg = {_RANDOM[2'h2][31:1], _RANDOM[2'h3][0]};
        busyReg = _RANDOM[2'h3][1];
        burstCounter = _RANDOM[2'h3][3:2];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_wait_n = ~writePendingReg;
  assign io_out_wr = writePendingReg;
  assign io_out_addr = {addrReg[24:1], 1'h0};
  assign io_out_din = casez_tmp;
endmodule

