// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module CPU_1(
  input         clock,
  input         reset,
  output [15:0] io_addr,
  input  [7:0]  io_din,
  output [7:0]  io_dout,
  output        io_rd,
  output        io_wr,
  output        io_rfsh,
  output        io_mreq,
  output        io_iorq,
  input         io_int,
  input         io_nmi
);

  wire       _cpu_RESET_n;
  wire       _cpu_CEN;
  wire       _cpu_WAIT_n = 1'h1;
  wire       _cpu_INT_n;
  wire       _cpu_NMI_n;
  wire       _cpu_BUSRQ_n = 1'h1;
  wire       _cpu_MREQ_n;
  wire       _cpu_IORQ_n;
  wire       _cpu_RD_n;
  wire       _cpu_WR_n;
  wire       _cpu_RFSH_n;
  reg  [2:0] cen_value;
  always @(posedge clock) begin
    if (reset)
      cen_value <= 3'h0;
    else
      cen_value <= 3'(cen_value + 3'h1);
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        cen_value = _RANDOM[/*Zero width*/ 1'b0][2:0];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign _cpu_RESET_n = ~reset;
  assign _cpu_CEN = &cen_value;
  assign _cpu_INT_n = ~io_int;
  assign _cpu_NMI_n = ~io_nmi;
  T80s cpu (
    .RESET_n (_cpu_RESET_n),
    .CLK     (clock),
    .CEN     (_cpu_CEN),
    .WAIT_n  (_cpu_WAIT_n),
    .INT_n   (_cpu_INT_n),
    .NMI_n   (_cpu_NMI_n),
    .BUSRQ_n (_cpu_BUSRQ_n),
    .M1_n    (/* unused */),
    .MREQ_n  (_cpu_MREQ_n),
    .IORQ_n  (_cpu_IORQ_n),
    .RD_n    (_cpu_RD_n),
    .WR_n    (_cpu_WR_n),
    .RFSH_n  (_cpu_RFSH_n),
    .HALT_n  (/* unused */),
    .BUSAK_n (/* unused */),
    .A       (io_addr),
    .DI      (io_din),
    .DO      (io_dout),
    .REG     (/* unused */)
  );
  assign io_rd = ~_cpu_RD_n;
  assign io_wr = ~_cpu_WR_n;
  assign io_rfsh = ~_cpu_RFSH_n;
  assign io_mreq = ~_cpu_MREQ_n;
  assign io_iorq = ~_cpu_IORQ_n;
endmodule

