// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module NMK112(
  input         clock,
  input         io_cpu_wr,
  input  [22:0] io_cpu_addr,
  input  [15:0] io_cpu_din,
  input  [24:0] io_addr_0_in,
  output [24:0] io_addr_0_out,
  input  [24:0] io_addr_1_in,
  output [24:0] io_addr_1_out
);

  reg  [4:0] pageTableReg_0_0;
  reg  [4:0] pageTableReg_0_1;
  reg  [4:0] pageTableReg_0_2;
  reg  [4:0] pageTableReg_0_3;
  reg  [4:0] pageTableReg_1_0;
  reg  [4:0] pageTableReg_1_1;
  reg  [4:0] pageTableReg_1_2;
  reg  [4:0] pageTableReg_1_3;
  reg  [4:0] casez_tmp;
  always @(*) begin
    casez (io_addr_0_in[17:16])
      2'b00:
        casez_tmp = pageTableReg_0_0;
      2'b01:
        casez_tmp = pageTableReg_0_1;
      2'b10:
        casez_tmp = pageTableReg_0_2;
      default:
        casez_tmp = pageTableReg_0_3;
    endcase
  end // always @(*)
  reg  [4:0] casez_tmp_0;
  wire [1:0] io_addr_1_out_bank =
    io_addr_1_in > 25'h400 ? io_addr_1_in[17:16] : io_addr_1_in[9:8];
  always @(*) begin
    casez (io_addr_1_out_bank)
      2'b00:
        casez_tmp_0 = pageTableReg_1_0;
      2'b01:
        casez_tmp_0 = pageTableReg_1_1;
      2'b10:
        casez_tmp_0 = pageTableReg_1_2;
      default:
        casez_tmp_0 = pageTableReg_1_3;
    endcase
  end // always @(*)
  wire       _GEN = io_cpu_addr[1:0] == 2'h0;
  wire       _GEN_0 = io_cpu_addr[1:0] == 2'h1;
  wire       _GEN_1 = io_cpu_addr[1:0] == 2'h2;
  always @(posedge clock) begin
    if (io_cpu_wr & ~(io_cpu_addr[2]) & _GEN)
      pageTableReg_0_0 <= io_cpu_din[4:0];
    if (io_cpu_wr & ~(io_cpu_addr[2]) & _GEN_0)
      pageTableReg_0_1 <= io_cpu_din[4:0];
    if (io_cpu_wr & ~(io_cpu_addr[2]) & _GEN_1)
      pageTableReg_0_2 <= io_cpu_din[4:0];
    if (io_cpu_wr & ~(io_cpu_addr[2]) & (&(io_cpu_addr[1:0])))
      pageTableReg_0_3 <= io_cpu_din[4:0];
    if (io_cpu_wr & io_cpu_addr[2] & _GEN)
      pageTableReg_1_0 <= io_cpu_din[4:0];
    if (io_cpu_wr & io_cpu_addr[2] & _GEN_0)
      pageTableReg_1_1 <= io_cpu_din[4:0];
    if (io_cpu_wr & io_cpu_addr[2] & _GEN_1)
      pageTableReg_1_2 <= io_cpu_din[4:0];
    if (io_cpu_wr & io_cpu_addr[2] & (&(io_cpu_addr[1:0])))
      pageTableReg_1_3 <= io_cpu_din[4:0];
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;
        end
        pageTableReg_0_0 = _RANDOM[1'h0][4:0];
        pageTableReg_0_1 = _RANDOM[1'h0][9:5];
        pageTableReg_0_2 = _RANDOM[1'h0][14:10];
        pageTableReg_0_3 = _RANDOM[1'h0][19:15];
        pageTableReg_1_0 = _RANDOM[1'h0][24:20];
        pageTableReg_1_1 = _RANDOM[1'h0][29:25];
        pageTableReg_1_2 = {_RANDOM[1'h0][31:30], _RANDOM[1'h1][2:0]};
        pageTableReg_1_3 = _RANDOM[1'h1][7:3];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_addr_0_out = {4'h0, casez_tmp, io_addr_0_in[15:0]};
  assign io_addr_1_out = {4'h0, casez_tmp_0, io_addr_1_in[15:0]};
endmodule

