// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module PageFlipper_1(
  input         clock,
  input         reset,
  input         io_mode,
  input         io_swapRead,
  input         io_swapWrite,
  output [31:0] io_addrRead,
  output [31:0] io_addrWrite
);

  reg  [1:0] rdIndexReg;
  reg  [1:0] wrIndexReg;
  wire       _wrIndexReg_T_11 = rdIndexReg == 2'h1;
  wire       _wrIndexReg_T_7 = wrIndexReg == 2'h1;
  wire       _rdIndexReg_T_11 = wrIndexReg == 2'h1;
  wire       _rdIndexReg_T_7 = rdIndexReg == 2'h1;
  wire       _wrIndexReg_T_27 = rdIndexReg == 2'h1;
  wire       _wrIndexReg_T_23 = wrIndexReg == 2'h1;
  always @(posedge clock) begin
    if (reset) begin
      rdIndexReg <= 2'h0;
      wrIndexReg <= 2'h1;
    end
    else if (io_mode) begin
      if (io_swapRead & io_swapWrite) begin
        rdIndexReg <= wrIndexReg;
        wrIndexReg <=
          ~(|wrIndexReg) & _wrIndexReg_T_11 | _wrIndexReg_T_7 & ~(|rdIndexReg)
            ? 2'h2
            : {1'h0,
               ~(_wrIndexReg_T_7 & rdIndexReg == 2'h2 | wrIndexReg == 2'h2
                 & _wrIndexReg_T_11)};
      end
      else begin
        if (io_swapRead)
          rdIndexReg <=
            ~(|rdIndexReg) & _rdIndexReg_T_11 | _rdIndexReg_T_7 & ~(|wrIndexReg)
              ? 2'h2
              : {1'h0,
                 ~(_rdIndexReg_T_7 & wrIndexReg == 2'h2 | rdIndexReg == 2'h2
                   & _rdIndexReg_T_11)};
        if (io_swapRead | ~io_swapWrite) begin
        end
        else
          wrIndexReg <=
            ~(|wrIndexReg) & _wrIndexReg_T_27 | _wrIndexReg_T_23 & ~(|rdIndexReg)
              ? 2'h2
              : {1'h0,
                 ~(_wrIndexReg_T_23 & rdIndexReg == 2'h2 | wrIndexReg == 2'h2
                   & _wrIndexReg_T_27)};
      end
    end
    else if (io_swapWrite) begin
      rdIndexReg <= {1'h0, wrIndexReg[0]};
      wrIndexReg <= {1'h0, ~(wrIndexReg[0])};
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        rdIndexReg = _RANDOM[/*Zero width*/ 1'b0][1:0];
        wrIndexReg = _RANDOM[/*Zero width*/ 1'b0][3:2];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_addrRead = {11'h120, rdIndexReg, 19'h0};
  assign io_addrWrite = {11'h120, wrIndexReg, 19'h0};
endmodule

