// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module PISO(
  input        clock,
  input        reset,
  input        io_rd,
  input        io_wr,
  output       io_isEmpty,
  output       io_isAlmostEmpty,
  input  [7:0] io_din_0,
  input  [7:0] io_din_1,
  input  [7:0] io_din_2,
  input  [7:0] io_din_3,
  input  [7:0] io_din_4,
  input  [7:0] io_din_5,
  input  [7:0] io_din_6,
  input  [7:0] io_din_7,
  input  [7:0] io_din_8,
  input  [7:0] io_din_9,
  input  [7:0] io_din_10,
  input  [7:0] io_din_11,
  input  [7:0] io_din_12,
  input  [7:0] io_din_13,
  input  [7:0] io_din_14,
  input  [7:0] io_din_15,
  output [7:0] io_dout
);

  reg  [7:0] pisoReg_0;
  reg  [7:0] pisoReg_1;
  reg  [7:0] pisoReg_2;
  reg  [7:0] pisoReg_3;
  reg  [7:0] pisoReg_4;
  reg  [7:0] pisoReg_5;
  reg  [7:0] pisoReg_6;
  reg  [7:0] pisoReg_7;
  reg  [7:0] pisoReg_8;
  reg  [7:0] pisoReg_9;
  reg  [7:0] pisoReg_10;
  reg  [7:0] pisoReg_11;
  reg  [7:0] pisoReg_12;
  reg  [7:0] pisoReg_13;
  reg  [7:0] pisoReg_14;
  reg  [7:0] pisoReg_15;
  reg  [4:0] pisoCounterReg;
  wire       _GEN = io_rd & (|pisoCounterReg);
  always @(posedge clock) begin
    if (io_wr) begin
      pisoReg_0 <= io_din_0;
      pisoReg_1 <= io_din_1;
      pisoReg_2 <= io_din_2;
      pisoReg_3 <= io_din_3;
      pisoReg_4 <= io_din_4;
      pisoReg_5 <= io_din_5;
      pisoReg_6 <= io_din_6;
      pisoReg_7 <= io_din_7;
      pisoReg_8 <= io_din_8;
      pisoReg_9 <= io_din_9;
      pisoReg_10 <= io_din_10;
      pisoReg_11 <= io_din_11;
      pisoReg_12 <= io_din_12;
      pisoReg_13 <= io_din_13;
      pisoReg_14 <= io_din_14;
      pisoReg_15 <= io_din_15;
    end
    else if (_GEN) begin
      pisoReg_0 <= pisoReg_1;
      pisoReg_1 <= pisoReg_2;
      pisoReg_2 <= pisoReg_3;
      pisoReg_3 <= pisoReg_4;
      pisoReg_4 <= pisoReg_5;
      pisoReg_5 <= pisoReg_6;
      pisoReg_6 <= pisoReg_7;
      pisoReg_7 <= pisoReg_8;
      pisoReg_8 <= pisoReg_9;
      pisoReg_9 <= pisoReg_10;
      pisoReg_10 <= pisoReg_11;
      pisoReg_11 <= pisoReg_12;
      pisoReg_12 <= pisoReg_13;
      pisoReg_13 <= pisoReg_14;
      pisoReg_14 <= pisoReg_15;
      pisoReg_15 <= pisoReg_0;
    end
    if (reset)
      pisoCounterReg <= 5'h0;
    else if (io_wr)
      pisoCounterReg <= 5'h10;
    else if (_GEN)
      pisoCounterReg <= 5'(pisoCounterReg - 5'h1);
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        pisoReg_0 = _RANDOM[3'h0][7:0];
        pisoReg_1 = _RANDOM[3'h0][15:8];
        pisoReg_2 = _RANDOM[3'h0][23:16];
        pisoReg_3 = _RANDOM[3'h0][31:24];
        pisoReg_4 = _RANDOM[3'h1][7:0];
        pisoReg_5 = _RANDOM[3'h1][15:8];
        pisoReg_6 = _RANDOM[3'h1][23:16];
        pisoReg_7 = _RANDOM[3'h1][31:24];
        pisoReg_8 = _RANDOM[3'h2][7:0];
        pisoReg_9 = _RANDOM[3'h2][15:8];
        pisoReg_10 = _RANDOM[3'h2][23:16];
        pisoReg_11 = _RANDOM[3'h2][31:24];
        pisoReg_12 = _RANDOM[3'h3][7:0];
        pisoReg_13 = _RANDOM[3'h3][15:8];
        pisoReg_14 = _RANDOM[3'h3][23:16];
        pisoReg_15 = _RANDOM[3'h3][31:24];
        pisoCounterReg = _RANDOM[3'h4][4:0];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_isEmpty = ~(|pisoCounterReg);
  assign io_isAlmostEmpty = pisoCounterReg == 5'h1;
  assign io_dout = pisoReg_0;
endmodule

