// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ReadDataFreezer_1(
  input         clock,
  input         reset,
  input         io_targetClock,
  input         io_in_rd,
  input  [24:0] io_in_addr,
  output [7:0]  io_in_dout,
  output        io_in_wait_n,
  output        io_in_valid,
  output        io_out_rd,
  output [24:0] io_out_addr,
  input  [7:0]  io_out_dout,
  input         io_out_wait_n,
  input         io_out_valid
);

  reg        clear_s;
  reg        clear_REG;
  wire       clear = clear_s ^ clear_REG;
  reg        wait_n_enableReg;
  reg        valid_enableReg;
  wire       valid = io_out_valid | valid_enableReg & ~clear;
  reg  [7:0] data_dataReg;
  reg        data_enableReg;
  reg        pendingRead;
  reg        clearRead_REG;
  wire       clearRead = clear & clearRead_REG;
  always @(posedge io_targetClock) begin
    if (reset)
      clear_s <= 1'h0;
    else
      clear_s <= ~clear_s;
  end // always @(posedge)
  always @(posedge clock) begin
    clear_REG <= clear_s;
    if (io_out_valid)
      data_dataReg <= io_out_dout;
    clearRead_REG <= valid;
    if (reset) begin
      wait_n_enableReg <= 1'h0;
      valid_enableReg <= 1'h0;
      data_enableReg <= 1'h0;
      pendingRead <= 1'h0;
    end
    else begin
      wait_n_enableReg <= io_out_wait_n | ~clear & wait_n_enableReg;
      valid_enableReg <= io_out_valid | ~clear & valid_enableReg;
      data_enableReg <= ~clear & (io_out_valid | data_enableReg);
      pendingRead <= io_in_rd & io_out_wait_n | ~clearRead & pendingRead;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        clear_s = _RANDOM[/*Zero width*/ 1'b0][0];
        clear_REG = _RANDOM[/*Zero width*/ 1'b0][1];
        wait_n_enableReg = _RANDOM[/*Zero width*/ 1'b0][2];
        valid_enableReg = _RANDOM[/*Zero width*/ 1'b0][3];
        data_dataReg = _RANDOM[/*Zero width*/ 1'b0][11:4];
        data_enableReg = _RANDOM[/*Zero width*/ 1'b0][12];
        pendingRead = _RANDOM[/*Zero width*/ 1'b0][13];
        clearRead_REG = _RANDOM[/*Zero width*/ 1'b0][14];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_dout = data_enableReg & ~clear ? data_dataReg : io_out_dout;
  assign io_in_wait_n = io_out_wait_n | wait_n_enableReg & ~clear;
  assign io_in_valid = valid;
  assign io_out_rd = io_in_rd & (~pendingRead | clearRead);
  assign io_out_addr = io_in_addr;
endmodule

