// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module YM2203(
  input         clock,
  input         reset,
  input         io_cpu_wr,
  input         io_cpu_addr,
  input  [7:0]  io_cpu_din,
  output [7:0]  io_cpu_dout,
  output        io_irq,
  output        io_audio_valid,
  output [15:0] io_audio_bits_psg,
  output [15:0] io_audio_bits_fm
);

  wire        _m_cs_n = 1'h0;
  wire        _m_wr_n;
  wire        _m_irq_n;
  wire [9:0]  _m_psg_snd;
  reg  [15:0] m_io_cen_counter;
  reg         m_io_cen_clockEnable;
  wire [16:0] m_io_cen_next = 17'({1'h0, m_io_cen_counter} + 17'h2000);
  always @(posedge clock) begin
    m_io_cen_counter <= m_io_cen_next[15:0];
    m_io_cen_clockEnable <= m_io_cen_next[16];
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        m_io_cen_counter = _RANDOM[/*Zero width*/ 1'b0][15:0];
        m_io_cen_clockEnable = _RANDOM[/*Zero width*/ 1'b0][16];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign _m_wr_n = ~io_cpu_wr;
  jt03 m (
    .rst        (reset),
    .clk        (clock),
    .cen        (m_io_cen_clockEnable),
    .din        (io_cpu_din),
    .addr       (io_cpu_addr),
    .cs_n       (_m_cs_n),
    .wr_n       (_m_wr_n),
    .dout       (io_cpu_dout),
    .irq_n      (_m_irq_n),
    .psg_snd    (_m_psg_snd),
    .fm_snd     (io_audio_bits_fm),
    .snd_sample (io_audio_valid)
  );
  assign io_irq = ~_m_irq_n;
  assign io_audio_bits_psg = {1'h0, _m_psg_snd, 5'h0};
endmodule

