// This file is a Codex-assisted rewrite based on the original work of
// Josh Bassett (nullobject).

module MazingerMainMap(
  input         clock,
  input         reset,
  input         game_active,
  input  [22:0] cpu_addr,
  input  [2:0]  cpu_fc,
  input         cpu_as,
  input         cpu_rw,
  input         read_strobe,
  input         write_strobe,
  input         prog_rom_valid,
  input         dtack_reg,
  input  [14:0] main_ram_addr,
  input  [1:0]  main_ram_mask,
  input  [15:0] cpu_dout,
  input         agallet_irq,
  input         unknown_irq,
  input         video_irq,
  input  [15:0] input1_data,
  input  [15:0] input0_data,
  input  [15:0] palette_data,
  input  [15:0] layer0_regs_data,
  input  [15:0] layer1_regs_data,
  input  [15:0] layer0_vram8_data,
  input  [15:0] layer1_vram8_data,
  input  [15:0] sound_data,
  input  [15:0] sprite_ram_data,
  input  [15:0] main_ram_data,
  input  [15:0] prog_rom_data,
  output [23:0] cpu_byte_addr,
  output        prog_rom_select,
  output        main_ram_select,
  output        sprite_ram_select,
  output        video_regs_select,
  output        irq_select,
  output        sprite_regs_select,
  output        sprite_swap_write,
  output        sound_select,
  output        sound_read,
  output        sound_write,
  output        layer1_vram8_select,
  output        layer0_vram8_select,
  output        layer1_regs_select,
  output        layer0_regs_select,
  output        input0_cycle,
  output        input1_cycle,
  output        input0_read,
  output        input1_read,
  output        eeprom_cycle,
  output        eeprom_write,
  output        palette_select,
  output [14:0] palette_ram_addr,
  output        extra_rom_select,
  output        no_op_select,
  output        prog_rom_access,
  output        prog_rom_ready,
  output        irq_read,
  output [1:0]  irq_word_offset,
  output        video_irq_clear,
  output        unknown_irq_clear,
  output        sync_dtack,
  output        cycle,
  output        unmapped_cycle,
  output        prog_rom_read,
  output        main_ram_read,
  output        main_ram_write,
  output        sprite_ram_read,
  output        sprite_ram_write,
  output        layer0_vram8_read,
  output        layer1_vram8_read,
  output        layer0_vram8_write,
  output        layer1_vram8_write,
  output        video_regs_read,
  output        video_regs_write,
  output        layer0_regs_read,
  output        layer1_regs_read,
  output        layer0_regs_write,
  output        layer1_regs_write,
  output        palette_read,
  output        palette_write,
  output        sprite_regs_write,
  output        cpu_space,
  output        open_bus_select,
  output        dtack,
  output        cpu_reset,
  output        boot_ram_select,
  output [15:0] boot_ram_dout,
  output        boot_watchdog_armed,
  output        boot_watchdog_delay_active,
  output        boot_watchdog_reset_active,
  output        boot_marker_write,
  output        boot_watchdog_trip,
  output        read_data_valid,
  output [15:0] read_data
);
  wire [15:0] irqCause =
    {13'h0, ~((irq_word_offset == 2'h0) & agallet_irq), ~unknown_irq, ~video_irq};

  MazingerMainDecoder decoder(
    .game_active          (game_active),
    .cpu_addr             (cpu_addr),
    .cpu_fc               (cpu_fc),
    .cpu_as               (cpu_as),
    .cpu_rw               (cpu_rw),
    .read_strobe          (read_strobe),
    .write_strobe         (write_strobe),
    .prog_rom_valid       (prog_rom_valid),
    .dtack_reg            (dtack_reg),
    .cpu_byte_addr        (cpu_byte_addr),
    .prog_rom_select      (prog_rom_select),
    .main_ram_select      (main_ram_select),
    .sprite_ram_select    (sprite_ram_select),
    .video_regs_select    (video_regs_select),
    .irq_select           (irq_select),
    .sprite_regs_select   (sprite_regs_select),
    .sprite_swap_write    (sprite_swap_write),
    .sound_select         (sound_select),
    .sound_read           (sound_read),
    .sound_write          (sound_write),
    .layer1_vram8_select  (layer1_vram8_select),
    .layer0_vram8_select  (layer0_vram8_select),
    .layer1_regs_select   (layer1_regs_select),
    .layer0_regs_select   (layer0_regs_select),
    .input0_select        (),
    .input1_select        (),
    .input0_cycle         (input0_cycle),
    .input1_cycle         (input1_cycle),
    .input0_read          (input0_read),
    .input1_read          (input1_read),
    .eeprom_select        (),
    .eeprom_cycle         (eeprom_cycle),
    .eeprom_write         (eeprom_write),
    .palette_select       (palette_select),
    .palette_ram_addr     (palette_ram_addr),
    .extra_rom_select     (extra_rom_select),
    .no_op_select         (no_op_select),
    .prog_rom_access      (prog_rom_access),
    .prog_rom_ready       (prog_rom_ready),
    .irq_read             (irq_read),
    .irq_word_offset      (irq_word_offset),
    .video_irq_clear      (video_irq_clear),
    .unknown_irq_clear    (unknown_irq_clear),
    .sync_dtack           (sync_dtack),
    .cycle                (cycle),
    .known_select         (),
    .unmapped_cycle       (unmapped_cycle),
    .prog_rom_read        (prog_rom_read),
    .main_ram_read        (main_ram_read),
    .main_ram_write       (main_ram_write),
    .sprite_ram_read      (sprite_ram_read),
    .sprite_ram_write     (sprite_ram_write),
    .layer0_vram8_read    (layer0_vram8_read),
    .layer1_vram8_read    (layer1_vram8_read),
    .layer0_vram8_write   (layer0_vram8_write),
    .layer1_vram8_write   (layer1_vram8_write),
    .video_regs_read      (video_regs_read),
    .video_regs_write     (video_regs_write),
    .layer0_regs_read     (layer0_regs_read),
    .layer1_regs_read     (layer1_regs_read),
    .layer0_regs_write    (layer0_regs_write),
    .layer1_regs_write    (layer1_regs_write),
    .palette_read         (palette_read),
    .palette_write        (palette_write),
    .sprite_regs_write    (sprite_regs_write),
    .cpu_space            (cpu_space),
    .data_strobe          (),
    .open_bus_select      (open_bus_select),
    .dtack                (dtack)
  );

  assign boot_ram_select = main_ram_select & (main_ram_addr[14:1] == 14'd0);

  MazingerBootWatchdog bootWatchdog(
    .clock                  (clock),
    .reset                  (reset),
    .game_active            (game_active),
    .boot_ram_select        (boot_ram_select),
    .boot_ram_write         (main_ram_write),
    .boot_ram_word          (main_ram_addr[0]),
    .boot_ram_mask          (main_ram_mask),
    .boot_ram_din           (cpu_dout),
    .cpu_reset              (cpu_reset),
    .boot_ram_dout          (boot_ram_dout),
    .watchdog_armed         (boot_watchdog_armed),
    .watchdog_delay_active  (boot_watchdog_delay_active),
    .watchdog_reset_active  (boot_watchdog_reset_active),
    .boot_marker_write      (boot_marker_write),
    .watchdog_trip          (boot_watchdog_trip)
  );

  MazingerMainReadMux readMux(
    .input1_read         (input1_read),
    .input0_read         (input0_read),
    .palette_select      (palette_select),
    .layer0_regs_select  (layer0_regs_select),
    .layer1_regs_select  (layer1_regs_select),
    .layer0_vram8_select (layer0_vram8_select),
    .layer1_vram8_select (layer1_vram8_select),
    .sound_read          (sound_read),
    .irq_read            (irq_read),
    .sprite_ram_select   (sprite_ram_select),
    .boot_ram_select     (boot_ram_select),
    .main_ram_select     (main_ram_select),
    .no_op_read          (no_op_select & read_strobe),
    .prog_rom_ready      (prog_rom_ready),
    .open_bus_read       (open_bus_select & read_strobe),
    .input1_data         (input1_data),
    .input0_data         (input0_data),
    .palette_data        (palette_data),
    .layer0_regs_data    (layer0_regs_data),
    .layer1_regs_data    (layer1_regs_data),
    .layer0_vram8_data   (layer0_vram8_data),
    .layer1_vram8_data   (layer1_vram8_data),
    .sound_data          (sound_data),
    .irq_data            (irqCause),
    .sprite_ram_data     (sprite_ram_data),
    .boot_ram_data       (boot_ram_dout),
    .main_ram_data       (main_ram_data),
    .prog_rom_data       (prog_rom_data),
    .valid               (read_data_valid),
    .data                (read_data)
  );
endmodule
